#!/usr/bin/env bash
rm -rf _build ./gen-research.tar.gz
make html
tar -czvf gen-research.tar.gz  -C _build/html . 
sshpass -pkk0457 scp gen-research.tar.gz kurt@66.172.33.113:/var/www/kurttest.com/research
# Once uploaded, get rid of _build
rm -rf _build  ./gen-research.tar.gz
sshpass -pkk0457 ssh kurt@66.172.33.113 
